name: Build Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: login to dockerhub 
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin 

      - name: build New fronend image version2
        run : docker build -t frontend:v2  /frontendV2/Dockerfile .

      - name : tag image 
        run: docker tag frontend:v2  amrg6885/frontend:v2

      - name: push to docker hub 
        run: docker push amrg6885/frontend:v2

      - name: check images 
        run: docker images
